### ISSUE TITLE
"yo install qmui" error:fatal: could not create leading directories of 'UI_dev/qmui_web': Permission denied

### ISSUE THREAD

**Issue by crazypig13** [QMUI/generator-qmui#1]
```
[root@localhost qqq]# yo qmui

     _-----_     ╭──────────────────────────╮
    |       |    │  Welcome to the majestic │
    |--(o)--|    │      generator-qmui      │
   `---------´   │        generator!        │
    ( _´U`_ )    ╰──────────────────────────╯
    /___A___\   /
     |  ~  |     
   __'.___.'__   
 ´   `  |° ´ Y ` 

[13:50:46] QMUI Config: 开始进入项目配置
? 项目名称: qqq
? 项目前缀（用于公共组件的 Class-name ）: qq
? 项目主样式表文件名 main.scss
? 是否开启模板引擎（增强静态模板 include，条件判断，传参等能力）? Yes
? 是否开启 BrowserSync（修改后自动刷新浏览器）? Yes
? BrowserSync 的端口号 3030
? 是否显示 BrowserSync 的日志 No
[13:50:48] QMUI Install: 写入项目结构
[13:50:48] QMUI Install: 安装最新版本的 QMUI Web
fatal: could not create leading directories of 'UI_dev/qmui_web': Permission denied

events.js:141
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /tmp/qqq/UI_dev/qmui_web/config.js
    at EditionInterface.exports._copySingle (/root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at module.exports.yeoman.Base.extend.writing (/root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/generators/app/index.js:124:13)
    at Object.<anonymous> (/root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/yeoman-generator/lib/base.js:439:23)
    at /root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/run-async/index.js:26:25
    at /root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/run-async/index.js:25:19
    at /root/download/node-v4.2.1-linux-x64/lib/node_modules/generator-qmui/node_modules/yeoman-generator/lib/base.js:440:9
    at processImmediate [as _immediateCallback] (timers.js:368:17)

```

**Comment by kayo5994** [comment]
Do a `sudo yo qmui`.

You have a permissions problem best solved by making a directory permissive.
